# Generated by Django 4.2.1 on 2023-06-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_film_genre_seance_delete_meeting_film_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='age_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='seance',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance', to='cinema.film'),
        ),
    ]
