# Generated by Django 4.2.1 on 2023-06-02 16:11

import cinema.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_genre_age_limit_alter_seance_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='datetime',
            field=models.DateTimeField(validators=[cinema.model_validators.check_correct_datetime]),
        ),
    ]
